name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # تثبيت كافة المكتبات ومنها matplotlib الضرورية للرسم البياني أوفلاين
        pip install "numpy<2.0.0" pandas openpyxl matplotlib pyinstaller

    - name: Build EXE with PyInstaller Clean Standard
      run: |
        # استخدام الاسم الرسمي للملف المرفوع على جيت هاب (tayeb.py)
        pyinstaller --noconsole --onedir --icon=icon.ico tayeb.py

    # ضغط المجلد الناتج بالكامل لسهولة النقل والاستخدام على الويندوز
    - name: Zip Artifact Folder
      run: |
        powershell Compress-Archive -Path dist/tayeb/* -DestinationPath dist/tayeb-windows-app.zip

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tayeb-windows-app
        path: dist/tayeb-windows-app.zip
